name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/pern-stack
            git pull origin main
            
            # Backend
            cd backend
            npm install
            pm2 restart backend || pm2 start npm --name backend -- start
            
            # Frontend
            cd ../frontend
            npm install
            pm2 restart frontend || pm2 start npm --name frontend -- run dev
