name: CI/CD - Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          request_pty: true
          debug: true
          script: |
            set -e
            echo "✅ Connected to EC2"
            cd /home/ubuntu/pern-stack
            git fetch origin main
            git reset --hard origin/main
            cd backend
            npm ci --omit=dev
            pm2 restart all || pm2 start backend/server.js --name pern-backend
            cd ../frontend
            npm ci
            npm run build
            sudo rsync -a --delete dist/ /var/www/pern-frontend/
            sudo nginx -t
            sudo systemctl reload nginx
            echo "🚀 Deployment finished successfully!"
