name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or master, whichever you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.6.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/pern-stack/backend
            git pull origin main
            npm install --production
            pm2 restart all || pm2 start backend/server.js --name "pern-backend"
            cd /home/ubuntu/pern-stack/frontend
            git pull origin main
            npm install
            npm run build
            sudo cp -r dist/* /var/www/pern-frontend/
            sudo systemctl restart nginx
