name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # or master, whichever you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/myproject   # path where your project is stored
            git pull origin main
            npm install --production
            npx prisma migrate deploy   # if you use Prisma
            pm2 restart all             # restart your Node backend

